// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://pcjfvrjmuedyytavtrhv.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjamZ2cmptdWVkeXl0YXZ0cmh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMwNzkyNDUsImV4cCI6MjA0ODY1NTI0NX0.1oiHR1ZQPJa1sGEdnMRqhVk-rh45hpJ7jYwS5R7S4ZE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);